# Generated by Django 3.1.4 on 2021-01-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20210102_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_fee',
            field=models.IntegerField(null=True),
        ),
    ]
