# Generated by Django 3.1.4 on 2021-01-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20210102_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='appointment_date',
            field=models.DateTimeField(null=True),
        ),
    ]
