# Generated by Django 3.1.4 on 2021-01-02 18:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_auto_20210102_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 1, 2, 18, 8, 35, 446821, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
