# Generated by Django 3.1.4 on 2021-01-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_patient_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='appointment_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='appointment_date',
            field=models.DateField(null=True),
        ),
    ]
