# Generated by Django 3.1.4 on 2021-01-02 18:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_auto_20210103_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='created_at',
        ),
        migrations.AddField(
            model_name='patient',
            name='created_at_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 1, 2, 18, 18, 46, 349783, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='created_at_time',
            field=models.TimeField(auto_now_add=True, default=datetime.datetime(2021, 1, 2, 18, 19, 5, 301995, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
