# Generated by Django 3.1.4 on 2021-01-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_auto_20210103_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='time',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
