# Generated by Django 3.1.4 on 2021-01-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20210103_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='appointment_date',
            field=models.DateTimeField(null=True),
        ),
    ]
