# Generated by Django 3.1.4 on 2021-01-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_auto_20210104_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='room_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='room_service',
            field=models.IntegerField(),
        ),
    ]
