# Generated by Django 3.1.4 on 2021-01-04 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_patientdischarge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdischarge',
            old_name='outed_date',
            new_name='release_date',
        ),
        migrations.AddField(
            model_name='patientdischarge',
            name='assign_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor'),
        ),
        migrations.AddField(
            model_name='patientdischarge',
            name='medicine_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientdischarge',
            name='other_charge',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
