# Generated by Django 3.1.1 on 2021-01-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_auto_20210105_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admitted',
            name='room_service',
        ),
        migrations.AddField(
            model_name='patientdischarge',
            name='room_service',
            field=models.IntegerField(null=True),
        ),
    ]
