# Generated by Django 3.1.1 on 2021-01-05 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0026_auto_20210105_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdischarge',
            name='admitted',
        ),
        migrations.RemoveField(
            model_name='patientdischarge',
            name='room_service',
        ),
        migrations.AddField(
            model_name='appointment',
            name='room_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='room_service',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patientdischarge',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.appointment'),
        ),
        migrations.DeleteModel(
            name='Admitted',
        ),
    ]
