# Generated by Django 3.1.1 on 2021-01-05 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0028_auto_20210105_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdischarge',
            name='admitted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.admitted'),
        ),
        migrations.AlterField(
            model_name='patientdischarge',
            name='assign_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor'),
        ),
        migrations.AlterField(
            model_name='patientdischarge',
            name='medicine_cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patientdischarge',
            name='other_charge',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patientdischarge',
            name='release_date',
            field=models.DateField(),
        ),
    ]
