# Generated by Django 3.1.1 on 2021-01-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0034_admitted_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='admitted',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admitted',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
