# Generated by Django 3.1.1 on 2021-01-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0035_auto_20210109_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='weekly_available',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
