# Generated by Django 3.1.1 on 2021-01-17 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0036_doctor_weekly_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_appointment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='symptoms_details',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(default='+880', max_length=14, unique=True),
        ),
    ]
