# Generated by Django 3.1.1 on 2021-01-17 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0039_remove_appointment_symptoms_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_appointment',
        ),
    ]
