# Generated by Django 3.1.1 on 2021-01-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0041_auto_20210117_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
